# -*- coding: utf-8 -*-
"""AI Project.ipynb

Automatically generated by Colab.

# change to add updates

Original file is located at
    https://colab.research.google.com/drive/1SksW_p0fXJc2udKOpdDkGgUk9ATa9s4d
"""

from google.colab import drive
drive.mount('/content/drive')

"""### Load Forecasting"""

import pandas as pd
data1 = pd.read_csv('/content/drive/Shareddrives/smart_home_datasets/smart_home_energy_consumption_large.csv')
data2 = pd.read_csv('/content/drive/Shareddrives/smart_home_datasets/smart-home-dataset.csv')

data1['Energy Consumption (kWh)'] = data1['Energy Consumption (kWh)'] * 100
data1

"""shksherry --> smart-home-dataset.csv
1. Unix Timestamp
2. Transaction ID
3. Appliance Usage - 0 for not in use, 1 for in use
4. Voltage Metrics:
--> Line Voltage: voltage level in the electrical line
--> Voltage: voltage level at the specific location
--> Apparent Power: combination of real and reactive power in the electrical system
5. Energy Consumption: energy consumed, generated randomly within a specific range
6. Bandwidth: capacity/speed at which data can be transmitted between devices
7. Offloading Decision: randomly selects between "Local" and "Remote"
"""

target_value = 224
matching_rows = data2[data2['Voltage'] == target_value]
matching_rows

#clean up the data to make it easier to work with
import matplotlib.pyplot as plt
data1.hist(figsize=(25, 50), bins=30)
plt.show()

#CLASSES FOR APPLIANCES WITHIN THE ROOMS
class Appliance:
   def __init__(self, t, name, location, voltage, on_or_off):
    self.obj_type = t #defines if the object is a room, or an appliance
    self.name = name
    self.location = location
   def print_info(self):
    print(self.obj_type)
    print(self.name)
   def is_room(self):
    if self.obj_type == "room":
      return True
    else:
      return False
   def is_appliance(self):
    if self.obj_type == "appliance":
      return True
    else:
      return False

rooms = ["kitchen", "bedroom"]

devices = {
    "light_kitchen": {"room": "kitchen", "state": "off"},
    "door_lock": {"state": "unlocked"}
}

sensors = {
    "motion_kitchen": False,
    "time": "22:00",
    "temperature": 72
}

rooms = ["livingroom", "kitchen", "office", "bathroom", "bedroom"]
new_room = []
for room in rooms:
  new_room.append(Appliance("room", room, "not applicable", "not applicable", "not applicable"))

toaster = Appliance("appliance", "toaster", "kitchen", "200", "off")
toaster.print_info()

+Motion("kitchen")
+Time("23:30")

TurnOnLight(room) <= Motion(room) & Night()
LockDoors() <= Time(t) & (t > "23:00")

rule_priority = {
    "sleep_rule": 2,
    "motion_rule": 1
}

"""# Rules

Convenience
"""

if motion_detected and is_night:
    action = "turn_on_light"

"""Safety/Security"""

if time > "23:00":
    action = "lock_doors"

if no_motion_for_hours:
    action = "activate_security_mode"

# add "away mode"

"""Energy-Saving/Efficiency"""

if no_motion:
    action = "turn_off_lights"

if temperature > 75:
    action = "turn_off_heater"

if bedtime:
    turn_off_all_lights()
    lock_doors()

if light_already_on:
    do_nothing

"""# Forward-Chaining Engine"""

def forward_chain(facts):
    actions = []

    if facts["motion_kitchen"] and is_night(facts["time"]):
        actions.append("turn_on_kitchen_light")

    if facts["time"] > "23:00":
        actions.append("lock_doors")

    return actions

"""# Basic Simulation Loop"""

# Simulate time passing and sensor updates
for t in ["21:00", "23:30"]:
    sensors["time"] = t
    sensors["motion_kitchen"] = True

    actions = forward_chain(sensors)
    print(actions)

"""# Learning"""

user_pref = {
    "sleep_time": "22:30"
}

if current_time > user_pref["sleep_time"]:
    actions.append("turn_off_lights")

"""# Test Cases"""

# Energy saving test
{"motion": False, "time": "20:00"} → expect: turn_off_light

# Security test
{"time": "23:30"} → expect: lock_doors

# Conflict test
{"motion": True, "time": "23:30"} → expect: follow priority rule

"""# Ethics Layer

User Control
"""

if user_override:
    stop_all_automation()

"""# Explainability Layer"""

print("Action: LockDoors because time > 23:00")
print("Turning off lights because no motion detected")

"""# User Interface

Features:
1. Sleep Time Slider
-> User can directly modify rules to define behavior
2. Override Toggle
-> Stops all automation instantly to simulate user control
3. Action Log
-> Records inputs, decisions, and time to help debug and explain system behavior
"""

import streamlit as st
from datetime import datetime

st.title("Smart Home AI System")

# -----------------------
# SESSION STATE (for log)
# -----------------------
if "history" not in st.session_state:
    st.session_state.history = []

# -----------------------
# USER INPUTS
# -----------------------
st.sidebar.header("User Settings")

sleep_time = st.sidebar.slider("Sleep Time", 0, 23, 22)
override = st.sidebar.toggle("Override System (Disable Automation)")

st.header("Sensor Inputs")
motion = st.checkbox("Motion detected in kitchen")
time = st.slider("Current Hour", 0, 23, 21)
temperature = st.slider("Temperature", 60, 90, 72)

# -----------------------
# AI LOGIC (Forward Chaining Style)
# -----------------------
actions = []
explanations = []

if not override:

    # Rule 1: Motion + Night → Light ON
    if motion and time >= 22:
        actions.append("Turn ON kitchen light")
        explanations.append("Motion detected AND it is night")

    # Rule 2: Late Night → Lock Doors
    if time >= 23:
        actions.append("Lock doors")
        explanations.append("Time is after 23:00")

    # Rule 3: Sleep Time → Turn OFF lights
    if time >= sleep_time:
        actions.append("Turn OFF lights")
        explanations.append(f"Time is after user sleep time ({sleep_time}:00)")

else:
    actions.append("Automation Paused")
    explanations.append("User override is enabled")

# -----------------------
# OUTPUT DISPLAY
# -----------------------
st.subheader("Actions")
for a in actions:
    st.write("•", a)

st.subheader("Why?")
for e in explanations:
    st.write("•", e)

# -----------------------
# ACTION LOG (HISTORY)
# -----------------------
timestamp = datetime.now().strftime("%H:%M:%S")

if st.button("Save to Action Log"):
    st.session_state.history.append({
        "time": timestamp,
        "inputs": {
            "motion": motion,
            "hour": time,
            "temp": temperature,
            "sleep_time": sleep_time,
            "override": override
        },
        "actions": actions
    })

st.subheader("Action Log")

if st.session_state.history:
    for entry in reversed(st.session_state.history):
        st.write(f"**[{entry['time']}]**")
        st.write(f"Inputs: {entry['inputs']}")
        st.write(f"Actions: {entry['actions']}")
        st.write("---")
else:
    st.write("No actions logged yet.")

if st.button("Clear Log"):
    st.session_state.history = []

"""# Main"""

streamlit run app.py
