# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hbKaMWNFIMxzr6D6wUn6HZLzm6T1Z3_t
"""

# data_loader.py

import os
import pandas as pd

# data1 = pd.read_csv("datasets/smart_home_energy.csv")
# data2 = pd.read_csv("datasets/smart_home_dataset.csv")

BASE_DIR = os.path.dirname(__file__)
DATA_DIR = os.path.join(BASE_DIR, "datasets")

def load_csv(filename):
    path = os.path.join(DATA_DIR, filename)

    if not os.path.exists(path):
        raise FileNotFoundError(f"Dataset not found: {path}")

    return pd.read_csv(path)

# Drop useless columns
def clean_columns(df):
    drop_cols = ["Transaction ID", "Bandwidth", "Offloading Decision"]

    for col in drop_cols:
        if col in df.columns:
            df = df.drop(columns=[col])

    return df

# Normalize time by converting to int hours
def normalize_time(df):

    if "time" in df.columns:
        return df

    if "Unix Timestamp" in df.columns:
        df["time"] = pd.to_datetime(df["Unix Timestamp"], unit='s').dt.hour

    return df

# Convert features to booleans
def create_boolean_features(df):

    # Motion detection
    if "Appliance Usage" in df.columns:
        df["motion"] = df["Appliance Usage"] == 1

    # Night detection
    df["is_night"] = df["time"] >= 22

    # No motion
    df["no_motion"] = ~df["motion"]

    return df

# Normalize temperature and energy
def normalize_values(df):

    if "Temperature" in df.columns:
        df["Temperature"] = df["Temperature"].clip(0, 120)

    if "Energy Consumption (kWh)" in df.columns:
        df["Energy Consumption (kWh)"] = df["Energy Consumption (kWh)"].fillna(0)

    return df

# Handle missing values
def handle_missing(df):
    return df.fillna(method="ffill")

# Convert rows to facts
def row_to_facts(row):

    return {
        "motion_kitchen": bool(row.get("motion", False)),
        "time": int(row.get("time", 0)),
        "temperature": float(row.get("Temperature", 72)),
        "is_night": bool(row.get("is_night", False))
    }

# PREPROCESS DATA FOR DATAFRAME
def preprocess_data(df):

    df = clean_columns(df)
    df = normalize_time(df)
    df = create_boolean_features(df)
    df = normalize_values(df)
    df = handle_missing(df)

    return df

# facts.py

# facts.py

class Facts:
    def __init__(self):
        self.data = {
            # --------------------
            # CORE SENSORS
            # --------------------
            "time": 21,
            "temperature": 72,

            "motion": {
                "kitchen": False,
                "bedroom": False,
                "livingroom": False
            },

            "presence": False,
            "ambient_light": 50,

            # --------------------
            # SYSTEM MODES
            # --------------------
            "mode": {
                "energy": False,
                "security": False
            },

            # --------------------
            # APPLIANCE STATE
            # --------------------
            "appliances": {
                "kitchen_light": "off",
                "livingroom_light": "off",
                "door_lock": "unlocked"
            },

            # --------------------
            # CONTROL FLAGS
            # --------------------
            "override": False,
            "appliance_override": False,
            "selected_room": "kitchen"
        }

    def update(self, key, value):
        self.data[key] = value

    def get(self):
        return self.data

# rules.py

class Rule:
    def __init__(self, name, condition, action, priority=1, explanation=""):
        self.name = name
        self.condition = condition
        self.action = action
        self.priority = priority
        self.explanation = explanation


# rules.py

def load_rules():

    return [

        # ----------------------------
        # ENERGY MODE RULES
        # ----------------------------
        Rule(
            name="energy_mode_lights_off",
            condition=lambda f:
                f["mode"]["energy"]
                and f["presence"] == False
                and f["appliances"]["kitchen_light"] == "on",

            action="turn_off_lights",
            priority=3,
            explanation="Energy mode: no presence → save power"
        ),

        Rule(
            name="ambient_light_saving",
            condition=lambda f:
                f["ambient_light"] > 70
                and f["appliances"]["kitchen_light"] == "on",

            action="turn_off_lights",
            priority=2,
            explanation="Room is bright → lights not needed"
        ),

        # ----------------------------
        # SECURITY MODE RULES
        # ----------------------------
        Rule(
            name="security_lock_doors",
            condition=lambda f:
                f["mode"]["security"]
                and f["time"] >= 22
                and f["appliances"]["door_lock"] == "unlocked",

            action="lock_doors",
            priority=4,
            explanation="Security mode active at night"
        ),

        # ----------------------------
        # PRESENCE RULES
        # ----------------------------
        Rule(
            name="presence_light_on",
            condition=lambda f:
                f["presence"]
                and f["motion"][f["selected_room"]]
                and f["appliances"][f[f"selected_room"] + "_light"] == "off",

            action="turn_on_room_light",
            priority=2,
            explanation="User present + motion detected"
        ),

        # ----------------------------
        # BASIC NIGHT SECURITY
        # ----------------------------
        Rule(
            name="night_lock",
            condition=lambda f:
                f["time"] >= 23
                and f["appliances"]["door_lock"] == "unlocked"
                and not f["appliance_override"],

            action="lock_doors",
            priority=3,
            explanation="Late night auto-lock"
        )
    ]

# engine.py

def forward_chain(facts, rules):

    actions = []
    explanations = []

    changed = True

    while changed:
        changed = False

        for rule in sorted(rules, key=lambda r: r.priority, reverse=True):

            if rule.condition(facts):

                if rule.action not in actions:

                    actions.append(rule.action)
                    explanations.append({
                        "action": rule.action,
                        "rule": rule.name,
                        "why": rule.explanation
                    })

                    # STATE UPDATE
                    apply_action(facts, rule.action)

                    changed = True

    return actions, explanations
    
def apply_action(facts, action):

    appliances = facts["appliances"]
    selected_room = facts["selected_room"]

    if facts["appliance_override"]:
        return

    # ------------------------
    # LIGHT CONTROL (ROOM-AWARE)
    # ------------------------
    if action == "turn_off_lights":
        appliances["kitchen_light"] = "off"
        appliances["livingroom_light"] = "off"

    elif action == "turn_on_room_light":
        key = f"{selected_room}_light"
        appliances[key] = "on"

    # ------------------------
    # SECURITY
    # ------------------------
    elif action == "lock_doors":
        appliances["door_lock"] = "locked"

    elif action == "unlock_doors":
        appliances["door_lock"] = "unlocked"

# explain.py

def format_explanations(explanations):

    output = []

    for e in explanations:
        output.append(
            f"Action: {e['action']}\n"
            f"Triggered by rule: {e['rule']}\n"
            f"Reason: {e['why']}\n"
        )

    return output

# simulation.py

import pandas as pd

def load_energy_data(path):

    df = pd.read_csv(path)

    df["Energy Consumption (kWh)"] *= 100

    return df


def simulate_time_series(df):

    # Convert dataset into pseudo-events
    events = []

    for _, row in df.head(50).iterrows():

        events.append({
            "time": int(row["Unix Timestamp"] % 24),
            "motion": row["Appliance Usage"] == 1,
            "temperature": row["Voltage"]
        })

    return events

# logger.py

import json
import os
from datetime import datetime

BASE_DIR = os.path.dirname(__file__)
LOG_FILE = os.path.join(BASE_DIR, "logs.json")


def log_event(event_type, data):
    log_entry = {
        "timestamp": datetime.now().isoformat(),
        "event_type": event_type,
        "data": data
    }

    # Load existing logs
    if os.path.exists(LOG_FILE):
        with open(LOG_FILE, "r") as f:
            logs = json.load(f)
    else:
        logs = []

    logs.append(log_entry)

    with open(LOG_FILE, "w") as f:
        json.dump(logs, f, indent=4)


def get_logs():
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        return json.load(f)


def clear_logs():
    if os.path.exists(LOG_FILE):
        os.remove(LOG_FILE)

# learning.py

from collections import Counter

# -----------------------------------
# 1. EXTRACT ACTIONS (FIXED)
# -----------------------------------
def extract_action_patterns(logs):

    actions = []

    for entry in logs:

        if entry["event_type"] == "inference_result":

            data = entry.get("data", {})
            actions.extend(data.get("actions", []))

    return Counter(actions)


# -----------------------------------
# 2. EXTRACT RULE FREQUENCY (NEW - IMPORTANT)
# -----------------------------------
def extract_rule_patterns(logs):

    rules = []

    for entry in logs:

        if entry["event_type"] == "inference_result":

            data = entry.get("data", {})
            explanations = data.get("explanations", [])

            for e in explanations:
                rules.append(e.get("rule"))

    return Counter(rules)


# -----------------------------------
# 3. TIME PATTERNS (IMPROVED)
# -----------------------------------
def extract_time_patterns(logs):

    time_map = {}

    for entry in logs:

        if entry["event_type"] == "sensor_update":

            hour = entry["data"].get("time")

            if hour is not None:
                time_map[hour] = time_map.get(hour, 0) + 1

    return time_map


# -----------------------------------
# 4. RULE GENERATION (NOW WORKS)
# -----------------------------------
def suggest_rules(action_counts, rule_counts, time_patterns):

    suggestions = []

    # --- ACTION-BASED LEARNING ---
    for action, count in action_counts.items():

        if count >= 2:   # LOWER threshold for your dataset

            if action == "turn_off_lights":
                suggestions.append({
                    "rule": "energy_saving_lights",
                    "logic": "if no motion → turn_off_lights",
                    "confidence": count
                })

    # --- RULE-BASED LEARNING ---
    for rule, count in rule_counts.items():

        if count >= 3:

            suggestions.append({
                "rule": f"reinforced_{rule}",
                "logic": f"strengthen existing rule: {rule}",
                "confidence": count
            })

    # --- TIME-BASED LEARNING ---
    for hour, freq in time_patterns.items():

        if freq >= 2 and hour >= 22:

            suggestions.append({
                "rule": "night_mode_auto_detected",
                "logic": f"if time >= {hour} → activate night behavior",
                "confidence": freq
            })

    return suggestions


# -----------------------------------
# 5. MAIN PIPELINE
# -----------------------------------
def run_learning(logs):

    action_counts = extract_action_patterns(logs)
    rule_counts = extract_rule_patterns(logs)
    time_patterns = extract_time_patterns(logs)

    return suggest_rules(action_counts, rule_counts, time_patterns)

# app.py

import streamlit as st
from datetime import datetime

# -----------------------------
# PAGE CONFIG
# -----------------------------
st.set_page_config(
    page_title="Smart Home AI",
    layout="wide",
    page_icon="🏠"
)

# -----------------------------
# INIT SYSTEM
# -----------------------------
facts = Facts()
rules = load_rules()

st.title("🏠 Smart Home AI System")
st.caption("Rule-based forward chaining AI with appliance-aware reasoning")

# -----------------------------
# SIDEBAR (CONTROL PANEL)
# -----------------------------
st.sidebar.header("⚙️ Smart Home Control Panel")

# -------------------------
# MODES
# -------------------------
st.sidebar.subheader("Modes")

energy_mode = st.sidebar.toggle("🌱 Energy Mode")
security_mode = st.sidebar.toggle("🔒 Security Mode")

# -------------------------
# ROOM SELECTOR
# -------------------------
st.sidebar.subheader("🏠 Room Control")

selected_room = st.sidebar.selectbox(
    "Active Room",
    ["kitchen", "bedroom", "livingroom"]
)

# -------------------------
# SENSOR INPUTS
# -------------------------
st.sidebar.subheader("📡 Sensors")

presence = st.sidebar.toggle("👤 Presence detected")
motion = st.sidebar.checkbox("Motion in selected room")
ambient_light = st.sidebar.slider("💡 Ambient Light", 0, 100, 50)

time = st.sidebar.slider("⏰ Hour", 0, 23, 21)
temperature = st.sidebar.slider("🌡 Temperature", 60, 90, 72)

# -------------------------
# OVERRIDE CONTROLS
# -------------------------
st.sidebar.subheader("🛑 Overrides")

override = st.sidebar.toggle("System Override")
appliance_override = st.sidebar.toggle("Appliance Override (manual control)")

# -----------------------------
# UPDATE FACTS
# -----------------------------
facts.update("time", time)
facts.update("temperature", temperature)
facts.update("override", override)
facts.update("appliance_override", appliance_override)
facts.update("selected_room", selected_room)
facts.update("presence", presence)
facts.update("ambient_light", ambient_light)

# modes
facts.data["mode"]["energy"] = energy_mode
facts.data["mode"]["security"] = security_mode

# room motion
facts.data["motion"][selected_room] = motion

log_event("sensor_update", facts.get())

# -----------------------------
# RUN INFERENCE
# -----------------------------
if not override:
    actions, explanations = forward_chain(facts.get(), rules)
else:
    actions = ["SYSTEM PAUSED"]
    explanations = [{
        "action": "none",
        "rule": "override",
        "why": "User disabled automation"
    }]

log_event("inference_result", {
    "actions": actions,
    "explanations": explanations
})

# -----------------------------
# MAIN DASHBOARD LAYOUT
# -----------------------------
col1, col2, col3 = st.columns(3)

# ---- COLUMN 1: ACTIONS ----
with col1:
    st.subheader("⚡ Actions")

    if actions:
        for a in actions:
            st.success(a)
    else:
        st.info("No actions triggered")

# ---- COLUMN 2: EXPLANATIONS ----
with col2:
    st.subheader("🧠 Reasoning")

    formatted = format_explanations(explanations)

    for f in formatted:
        st.code(f)

# ---- COLUMN 3: SYSTEM STATE ----
with col3:
    st.subheader("📊 Live State")
    st.json(facts.get())

# -----------------------------
# LEARNING SECTION
# -----------------------------
st.divider()

st.subheader("🧠 Learning Engine (Behavior Discovery)")

if st.button("Run Learning Analysis"):

    logs = get_logs()
    suggestions = run_learning(logs)

    if suggestions:

        for s in suggestions:
            st.markdown(f"### 🔹 {s['rule']}")
            st.write("**Logic:**", s["logic"])
            st.write("**Confidence:**", s["confidence"])
            st.divider()

    else:
        st.warning("No patterns found yet")

# -----------------------------
# LOG VIEWER (DEBUG PANEL)
# -----------------------------
with st.expander("📜 System Logs (Debug View)"):

    logs = get_logs()

    if logs:
        for entry in reversed(logs[-15:]):
            st.write(f"**{entry['timestamp']}** — {entry['event_type']}")
            st.json(entry["data"])
            st.divider()
    else:
        st.info("No logs available")

# -----------------------------
# SYSTEM ACTION BAR
# -----------------------------
st.divider()

colA, colB = st.columns(2)

with colA:
    if st.button("🧹 Clear Logs"):
        clear_logs()
        st.success("Logs cleared")

with colB:
    st.button("🔄 Refresh State")
